---
- name: install packaged dependencies
  apt:
    - name:
        - autoconf
        - automake
        - pkg-config
      state: present
- name: copy tmux configuration
  copy:
    src: tmux.conf
    dest: ~/.config/tmux/tmux.conf
