---
- name: install packaged dependencies
  become: true
  apt:
    name:
      - autoconf
      - automake
      - bison
      - build-essential
      - libevent-dev
      - lib32ncurses-dev
      - pkg-config
    state: present
- name: install tmux from latest git master
  become: true
  vars:
    tmux_source_dir: /usr/src/tmux
  block:
    - name: fetch source from git
      git:
        repo: https://github.com/tmux/tmux.git
        dest: "{{ tmux_source_dir }}"
    - name: run autogen
      shell:
        cmd: sh autogen.sh
        chdir: "{{ tmux_source_dir }}"
    - name: build from source
      shell:
        cmd: ./configure && make
        chdir: "{{ tmux_source_dir }}"
    - name: install
      shell:
        cmd: make install
        chdir: "{{ tmux_source_dir }}"
- name: apply tmux configuration
  vars:
    config_directory: "~/.config/tmux"
  block:
    - name: ensure existence of config directory
      file:
        path: "{{ config_directory }}"
        state: directory
    - name: copy tmux configuration
      copy:
        src: tmux.conf
        dest: "{{ config_directory }}"
